FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
ENV NODE_ENV=production
RUN npx prisma generate
RUN npm run build

RUN npm run build
EXPOSE 3000

CMD ["npm", "start"]